Srs Bolting
NeotokyoRebuild/neo pull request #259
Opened 2024-05-22 15:28 UTC by AdamTadeusz

Adds bolting the srs, prevents bolting and reloading when looking through scope and fire button is held, bolting animation supersedes running animation, weapons dropped before being bolted do not have a round in the chamber and have to be chambered on pickup

2024-05-22 17:17 UTC, AdamTadeusz commented
This also seems to fix the switching weapons to fire the srs faster problem

2024-05-26 11:15 UTC, nullsystem requested changes

2024-05-27 11:15 UTC, AdamTadeusz commented on mp/src/game/shared/neo/neo_player_shared.cpp
> +	if (!pWep || pWep->m_bInReload || pWep->GetRoundBeingChambered())
removed the assert, works fine now

2024-05-27 11:16 UTC, nullsystem approved these changes

2024-05-27 11:16 UTC, merged