Change ghost cap distance calculation to match GO NT.
NeotokyoRebuild/neo pull request #314
Opened 2024-05-30 19:12 UTC by Agiel

For parity the distance is calculated in 3D instead of 2D, and the cap zone radius is not halved. Also, a distance less than or equal to the radius should be a cap, not just less than (this caused some annoying off by a frame issues in one of my old plugins 😅).

Fixes #269.

2024-05-31 11:33 UTC, Rainyan commented
This is clearly better than what we had, but I think it's still slightly off from the original.

For example, comparing the van cap in nt_dawn:
```
map nt_dawn_ctg

// spawn a bot to the other team
sv_cheats 1; bot_add

// steps:
//   1. make sure you spawn in the outside, so your capzone is inside
//   2. go grab the ghost from the world

cl_showpos 1

// This teleports you just barely outside the capzone range.
// Might still not be quite 100% accurately the actual limit, but it's pretty close:
setpos -350 179.750344 -135; setang 0 -90 0

// This triggers the van cap for original NT:
setpos -350 179.750343 -135; setang 0 -90 0
```

For the remake, this limit is somewhere closer to `setpos -350 178.7 -135; setang 0 -90 0` before the cap actually goes in. So I think we're most likely off by 1 unit (~179.7 vs ~178.7) somewhere. Peeking at the disassembly, I think the original implementation calls `CEntitySphereQuery` for this, but I'm guessing we could just offset the calculation accordingly to get the same behaviour.

2024-05-31 12:42 UTC, AdamTadeusz submitted a review, later dismissed

2024-05-31 12:57 UTC, Rainyan requested changes
As per https://github.com/NeotokyoRebuild/neo/pull/314#issuecomment-2141845010

I'd be willing to merge, but in that case we shouldn't close #269 as this isn't full parity currently.

2024-05-31 13:10 UTC, Agiel commented
The off-by-one unit discrepancy is certainly weird, but I based nt-wincond off the disassembly and there's nothing weird going on there as far as I could tell https://github.com/Agiel/nt-wincond/blob/main/addons/sourcemod/scripting/nt_wincond.sp#L271.

Hopefully I'll have some time to dig into it this weekend, but if it's not something obvious I think it's fine to merge this and call it close enough.

2024-05-31 13:11 UTC, Rainyan approved these changes

2024-05-31 13:13 UTC, Rainyan commented
> The off-by-one unit discrepancy is certainly weird, but I based nt-wincond off the disassembly and there's nothing weird going on there as far as I could tell https://github.com/Agiel/nt-wincond/blob/main/addons/sourcemod/scripting/nt_wincond.sp#L271.
> 
> Hopefully I'll have some time to dig into it this weekend, but if it's not something obvious I think it's fine to merge this and call it close enough.

Alright. I think this is good to merge then, but we should re-open #269 until the possible distance discrepancy has been investigated.

2024-06-01 22:21 UTC, nullsystem approved these changes

2024-06-02 11:08 UTC, merged