Steam Avatar, healthbar and class on team Hud. Also partial fix to ammo display being to bright
NeotokyoRebuild/neo pull request #315
Opened 2024-05-31 14:04 UTC by AdamTadeusz

2024-05-31 20:03 UTC, nullsystem requested changes

2024-05-31 20:12 UTC, Agiel commented on mp/src/game/client/neo/ui/neo_hud_round_state.cpp
> +	V_sprintf_safe(m_szStatusANSI, "%s", prefixStr);
I'd say these are different things and we might even want to display them in different locations. "Freeze" modifies the timer (in og NT it's indicated by the random text spam in the bottom left corner but I think it's good to make it more centered), while "Match point" modifies the round counter (and should be placed nearby that).

2024-06-02 10:37 UTC, AdamTadeusz commented on mp/src/game/client/neo/ui/neo_hud_round_state.cpp
> +	V_sprintf_safe(m_szStatusANSI, "%s", prefixStr);
How about Freeze and Overtime are displayed _instead_ of the time, and Match Paint and Sudden death displayed under the round counter

2024-06-02 10:41 UTC, AdamTadeusz commented on mp/src/game/client/neo/ui/neo_hud_round_state.cpp
> +	V_sprintf_safe(m_szStatusANSI, "%s", prefixStr);
Or could have the timer tick down to zero during freeze in a different colour like in cs go, and tick up during overtime whenever that gets implemented

2024-06-02 11:50 UTC, nullsystem commented on mp/src/game/client/neo/ui/neo_hud_round_state.cpp
> +	V_sprintf_safe(m_szStatusANSI, "%s", prefixStr);
I think a timer ticking down on different color sounds good for freeze. Regarding overtime don't need to bother with that for now until it gets implemented.

2024-06-02 12:04 UTC, nullsystem approved these changes
LGTM, the red countdown looks good

2024-06-02 12:11 UTC, Agiel approved these changes
We really shouldn't be having non-code related design discussions in PR's. I'm fine with merging this for now, but it's going to need another design pass in a more appropriate forum.

2024-06-02 12:15 UTC, merged