Weapon innacuracy same between own shots and shots of others
NeotokyoRebuild/neo pull request #342
Opened 2024-06-06 22:16 UTC by AdamTadeusz

Use NEOShotManipulator both when shooting and when displaying other people's shots. When using shotguns, opt for the default ShotManipulator, as NEOShotManipulator does not match the expected behaviour of shotguns very well

2024-06-06 22:18 UTC, AdamTadeusz commented
actually it just occured to me I only change the shotgun c_te file, should go back and check what the other weapons are using

2024-06-10 16:15 UTC, Rainyan requested changes

2024-06-23 15:14 UTC, kassibuss commented
Shouldnt we get this merged for the next playtest?

2024-06-25 15:52 UTC, Rainyan commented on mp/src/game/shared/neo/weapons/weapon_aa13.h
> +	virtual const Vector& GetBulletSpread(void) OVERRIDE { return VECTOR_CONE_7DEGREES; };
This is dangling, because the referenced Vector goes out of scope when this returns. Should be declared as a static variable inside the function.

2024-06-25 16:48 UTC, Rainyan approved these changes

2024-06-26 17:31 UTC, nullsystem approved these changes

2024-06-26 22:17 UTC, merged