Motion Vision Working
NeotokyoRebuild/neo pull request #370
Opened 2024-06-15 12:24 UTC by VantoNortim

Now overrides cloak
Change material shader to ignore lighting and stop it from flickering

Still missing: 
Shader with gradient effect
Items/props having MV applied

2024-06-16 11:47 UTC, Rainyan requested changes

2024-06-16 11:47 UTC, Rainyan commented on mp/src/game/client/neo/c_neo_player.cpp
>  	int ret = BaseClass::DrawModel(flags);
If BaseClass is not ready to draw, we should probably return early here:
```cpp
if (!ret)
{
	return ret;
}
```
etc

2024-06-16 11:47 UTC, Rainyan commented on mp/src/game/client/neo/c_neo_player.cpp
> +		auto vel = GetAbsVelocity().Length2D();
Use `Length` instead of `Length2D`, so we also catch vertical motion for parity.

2024-06-16 11:49 UTC, Rainyan commented
> Still missing:
> Shader with gradient effect

I could look into this, and replace the current experimental MV with something more in line with parity.

2024-06-21 12:39 UTC, Rainyan approved these changes

2024-06-21 16:53 UTC, nullsystem approved these changes

2024-06-23 14:07 UTC, merged