Fadeout after death
NeotokyoRebuild/neo pull request #380
Opened 2024-06-17 22:12 UTC by nullsystem

* 3s fade, 1s stays on faded
* Effect local client/player after death 1st tick only
* fixes #143

2024-06-17 23:39 UTC, Rainyan requested changes

2024-06-17 23:39 UTC, Rainyan commented on mp/src/game/client/neo/c_neo_player.cpp
There's a bug with this fade triggering on initial team join.

We'll also need an un-fade using `FFADE_IN|FFADE_PURGE`, for parity.

Here's a very rough annotated estimation of OG NT fade timings:

[fade_annotated.webm](https://github.com/NeotokyoRebuild/neo/assets/6595066/9a00a95d-a496-4e48-9d6e-fba6fddc7481)

There does seem to be distinct long fade-out, and some sustain (probably the `duration` and `holdTime`), followed by a fade-in that purges the fade-out.

Perhaps we could do something like `SetObserverMode(OBS_MODE_DEATHCAM)` at `m_bFirstDeathTick` or wherever, and then override `C_BasePlayer::CalcDeathCamView` for handling that death camera & fade, using deltatime from `GetDeathTime()`.

We'd also wanna keep the camera fixed to the ragdoll(?) head position for parity, but that's kind of unrelated to this PR.

And once the fade sequence is completed, `SetObserverMode` back to whatever the user had selected before the deathcam sequence, so they can start observing as usual (and we stop calling `::CalcDeathCamView`).

2024-06-18 22:56 UTC, nullsystem commented on mp/src/game/client/neo/c_neo_player.cpp
@Rainyan Made the fade like OG:NT now and set the death cam at head position

2024-06-19 17:11 UTC, Rainyan approved these changes
Looks good.

One more thing I realised is that in OG NT, you can't start speccing your teammates until after the fadeout+hold periods (8+2 secs) - until then, pressing `+jump` or `+attack` does nothing. But in the rebuild, you can press `+jump` after dying and instantly jump to spectating. This might theoretically have some gameplay implications in competitive matches context etc.

Up to you whether you're interested in implementing it here or leave it for another day (in which case we probably want to open a bug for tracking it).

2024-06-19 22:01 UTC, nullsystem commented
@Rainyan I've implemented it in here. The button blocking is done similar to how freeze time does it, so there's server-side section this time. If statement made fairly restricted to only round live as: a) doesn't affect implication outside of live rounds, and b) would need more loaded to ensure it doesn't affect other situation if not simply restricted to live.

2024-06-19 22:39 UTC, Rainyan approved these changes

2024-06-26 08:50 UTC, AdamTadeusz approved these changes

2024-06-26 16:59 UTC, merged