Do not open class/loadout menu if you are spectating
NeotokyoRebuild/neo pull request #397
Opened 2024-06-24 16:39 UTC by VantoNortim

## Description
Do not open the Class or Loadout menu while being in team Spectate/Unassigned

## Toolchain
- Windows MSVC VS2022

## Linked Issues
- fixes #385

2024-06-24 19:17 UTC, nullsystem commented
@VantoNortim btw this branch is very behind the current master branch

2024-06-24 20:20 UTC, nullsystem approved these changes
Looks fine after rebasing it to latest master

2024-06-25 02:17 UTC, Rainyan requested changes
This prevents the  player from picking their class and loadout when they are first joining a playing team from spectator, because the associated `jointeam` command has not been processed yet.

The simplest solution is probably to just assign the client's team locally before these callbacks are invoked, for example:

```diff
diff --git a/mp/src/game/client/neo/game_controls/neo_teammenu.cpp b/mp/src/game/client/neo/game_controls/neo_teammenu.cpp
index 8658be7..1d095b0 100644
--- a/mp/src/game/client/neo/game_controls/neo_teammenu.cpp
+++ b/mp/src/game/client/neo/game_controls/neo_teammenu.cpp
@@ -177,6 +177,7 @@ void CNeoTeamMenu::OnCommand(const char *command)
 		const int nsfNumPlayers = (pNsf != NULL ? pNsf->Get_Number_Players() : 0);
 		int randomTeam = jinNumPlayers > nsfNumPlayers ? TEAM_NSF : (nsfNumPlayers > jinNumPlayers ? TEAM_JINRAI : RandomInt(TEAM_JINRAI, TEAM_NSF));
 		V_sprintf_safe(commandBuffer, "jointeam %i", randomTeam);
+		C_NEO_Player::GetLocalNEOPlayer()->m_iTeamNum = randomTeam;
 		ChangeMenu("classmenu");
 		engine->ClientCmd(commandBuffer);
 		return;
@@ -197,7 +198,25 @@ void CNeoTeamMenu::OnCommand(const char *command)
 	}
 
 	if (Q_stristr(commandBuffer, "jointeam") != 0) // Note using stristr, not strcmp. Equates to true when jointeam in commandBuffer
-	{ // joining jinrai or nsf
+	{ // joining something other than TEAM_SPECTATOR or TEAM_NONE
+		CUtlStringList strs;
+		V_SplitString(commandBuffer, "jointeam ", strs);
+		if (strs.Count() != 0)
+		{
+			char* szNum = strs[0];
+			const int len = V_strlen(szNum);
+			for (int i = 0; i < len; ++i)
+			{
+				if (!V_isdigit(szNum[i]))
+				{
+					szNum[i] = '\0';
+					break;
+				}
+			}
+			const int team = V_atoi(szNum);
+			C_NEO_Player::GetLocalNEOPlayer()->m_iTeamNum = team;
+		}
+
 		ChangeMenu("classmenu");
 		engine->ClientCmd(commandBuffer);
 		return;
```

But maybe double check that C string manipulation stuff :smile:

The `m_iTeamNum` is networked, so any discrepancy should get overwritten by the server once it has processed the team request.

2024-06-25 02:17 UTC, Rainyan commented on mp/src/game/client/neo/c_neo_player.cpp
> +		}
Nit: from the shareddefs header, using `if (GetLocalPlayerTeam() < FIRST_GAME_TEAM)` would be a way to express this more tersely.

2024-06-30 12:19 UTC, VantoNortim commented
> This prevents the player from picking their class and loadout when they are first joining a playing team from spectator, because the associated `jointeam` command has not been processed yet.
> 
> The simplest solution is probably to just assign the client's team locally before these callbacks are invoked, for example:
> 
> ```diff
> diff --git a/mp/src/game/client/neo/game_controls/neo_teammenu.cpp b/mp/src/game/client/neo/game_controls/neo_teammenu.cpp
> index 8658be7..1d095b0 100644
> --- a/mp/src/game/client/neo/game_controls/neo_teammenu.cpp
> +++ b/mp/src/game/client/neo/game_controls/neo_teammenu.cpp
> @@ -177,6 +177,7 @@ void CNeoTeamMenu::OnCommand(const char *command)
>  		const int nsfNumPlayers = (pNsf != NULL ? pNsf->Get_Number_Players() : 0);
>  		int randomTeam = jinNumPlayers > nsfNumPlayers ? TEAM_NSF : (nsfNumPlayers > jinNumPlayers ? TEAM_JINRAI : RandomInt(TEAM_JINRAI, TEAM_NSF));
>  		V_sprintf_safe(commandBuffer, "jointeam %i", randomTeam);
> +		C_NEO_Player::GetLocalNEOPlayer()->m_iTeamNum = randomTeam;
>  		ChangeMenu("classmenu");
>  		engine->ClientCmd(commandBuffer);
>  		return;
> @@ -197,7 +198,25 @@ void CNeoTeamMenu::OnCommand(const char *command)
>  	}
>  
>  	if (Q_stristr(commandBuffer, "jointeam") != 0) // Note using stristr, not strcmp. Equates to true when jointeam in commandBuffer
> -	{ // joining jinrai or nsf
> +	{ // joining something other than TEAM_SPECTATOR or TEAM_NONE
> +		CUtlStringList strs;
> +		V_SplitString(commandBuffer, "jointeam ", strs);
> +		if (strs.Count() != 0)
> +		{
> +			char* szNum = strs[0];
> +			const int len = V_strlen(szNum);
> +			for (int i = 0; i < len; ++i)
> +			{
> +				if (!V_isdigit(szNum[i]))
> +				{
> +					szNum[i] = '\0';
> +					break;
> +				}
> +			}
> +			const int team = V_atoi(szNum);
> +			C_NEO_Player::GetLocalNEOPlayer()->m_iTeamNum = team;
> +		}
> +
>  		ChangeMenu("classmenu");
>  		engine->ClientCmd(commandBuffer);
>  		return;
> ```
> 
> But maybe double check that C string manipulation stuff 😄
> 
> The `m_iTeamNum` is networked, so any discrepancy should get overwritten by the server once it has processed the team request, so there's no need to do super strict validation here.

I found a better way to do this, by just forcing the team change to execute first. This way it just works.

2024-06-30 13:17 UTC, Rainyan commented
I still can't see the class and loadout menus appear. Breakpointing on the `engine->ExecuteClientCmd`, and then continuing execution makes them appear, but just running the game I get:

* Pick team
* No further menus appear to choose from
* You just sort of spawn as assault + MPN

2024-06-30 15:46 UTC, Rainyan commented
[class_loadout.webm](https://github.com/NeotokyoRebuild/neo/assets/6595066/ca3a7533-77de-4eee-9338-db45ebfa67ed)

Well, it's still doing this thing for me where I can't choose a class or loadout. 🤷‍♂️

2024-06-30 16:21 UTC, AdamTadeusz commented
> class_loadout.webm
> 
> Well, it's still doing this thing for me where I can't choose a class or loadout. 🤷‍♂️ Perhaps someone else should test this on their machine to see if it's an issue on my end.

Is this on a dedicated server? Just tested on a listen server and having no trouble selecting team and loadout

2024-06-30 16:27 UTC, Rainyan commented
> Is this on a dedicated server?

This is listen server. I've tried with a full rebuild and it still occurs. But I guess it's verified an issue on my end then, whatever it is.

2024-06-30 16:29 UTC, AdamTadeusz commented
I noticed on dedicated the class selection menu doesn;t open up after pickign a team like on a listen server, but I can still use f2 to open it and select that way. Now I gotta check master to see whether the same behaviour is on there

2024-06-30 16:34 UTC, AdamTadeusz commented
> > Is this on a dedicated server?
> 
> This is listen server. I've tried with a full rebuild and it still occurs. But I guess it's verified an issue on my end then, whatever it is.

So statistically speaking 33% of the playerbase will not be able to select their class after they join a server?

2024-06-30 16:39 UTC, VantoNortim commented
I am going to need more time to look into this then, I would have thought there is an event client side when the player switches teams. Maybe I should clean up opening those elements in general there are so many bools in the player class related to them. But surely we could just check if any of them are visible and so on.

2024-06-30 16:42 UTC, AdamTadeusz requested changes
Yeah I wouldn't pull this in right now since when joining a team on a dedicated server when you are initially a spectator the class menu doesn't open up.

Probably something to do with latency where on low latency your client picks up that you successfully joined a team and opens the menu in time, but with higher latency the client thinks you're still a spectator when it checks whether it should open the menu so doesn't show the menu the first time around

While using the keybind still seems to work for me I think most people might not be aware of the bind and thus can not pick their class

2024-06-30 16:44 UTC, AdamTadeusz commented on mp/src/game/client/neo/c_neo_player.cpp
> +		if (team == TEAM_UNASSIGNED || team == TEAM_SPECTATOR) {
Can probably use FIRST_GAME_TEAM here same as in neoloadoutmenu

2024-06-30 17:03 UTC, AdamTadeusz commented
I noticed you were setting the value of m_iTeam locally before making a request to change the local player's team to that team via a command, so I changed how the function to open the class and loadout menus check what team the local player is on to this and now the problems I mentioned before are gone 
![image](https://github.com/NeotokyoRebuild/neo/assets/44210793/36facfce-f0a7-466a-b48f-dd9806c4d21e)

2024-06-30 17:39 UTC, VantoNortim commented
> I noticed you were setting the value of m_iTeam locally before making a request to change the local player's team to that team via a command, so I changed how the function to open the class and loadout menus check what team the local player is on to this and now the problems I mentioned before are gone ![image](https://private-user-images.githubusercontent.com/44210793/344482019-36facfce-f0a7-466a-b48f-dd9806c4d21e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3Njg1NzMsIm5iZiI6MTcxOTc2ODI3MywicGF0aCI6Ii80NDIxMDc5My8zNDQ0ODIwMTktMzZmYWNmY2UtZjBhNy00NjZhLWI0OGYtZGQ5ODA2YzRkMjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE3MjQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OTdhYTFlMGUyZDM1YTk4MTQwMjcwMmE1NGUyZGVjMzgwZGUzZTI5MjZlZGRiMWMwNmFjNjcxMGQyNTIxZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.57BJEvwHcCS1Cvurrn9qeQqhJPkqHE8ywi1zxwX2qU4)
> 
> @Rainyan Could you do the same things I did in the two functions on line 216 and 293 and then see if the problem is resolved?
> 
> (edit) this is in c_neo_player
> 
> (edit 2) doing it this way isn't actually any different from the original, I have no clue why this fixed it for me, probably still a race condition thing

Yeah I think I will have to hook on the team change event sent by server and once that is ran I will show the class menu.

2024-07-01 16:47 UTC, closed without merging