Old Squad HUD
NeotokyoRebuild/neo pull request #523
Opened 2024-07-27 13:39 UTC by AdamTadeusz

## Description

Old Squad HUD plus some adjustments

## Toolchain

- Windows MSVC VS2022

## Linked Issues

- fixes #145

2024-07-27 13:40 UTC, AdamTadeusz commented
![image](https://github.com/user-attachments/assets/3d5a7253-a803-45ac-9b21-14e0ea7f9e27)
In the original the squad marker doesn't change size regardless of window size and aspect artio

2024-07-27 21:09 UTC, Rainyan commented
> In the original the squad marker doesn't change size regardless of window size and aspect artio

We might at least want a cvar for controlling this even if not parity - otherwise players on very large resolutions will have a hard time seeing the HUD, and same with very low resolutions rendering unreasonably large icons.

I'd suggest something like:
* value `0`: hardcoded size (parity)
* other values: scale from baseline, for example `value*res/1080p`, so a value of `1.5` at 1920x1080 would render the icons at 1.5x scaling.

2024-07-27 23:16 UTC, AdamTadeusz commented
> > In the original the squad marker doesn't change size regardless of window size and aspect artio
> 
> We might at least want a cvar for controlling this even if not parity - otherwise players on very large resolutions (4k+) will have a hard time seeing the HUD, and same with very low resolutions rendering unreasonably large icons.
> 
> I'd suggest something like:
> 
>     * value `0`: hardcoded size (parity)
> 
>     * other values: scale from baseline, for example `value*(res/1080p)`, so a value of `1.5` would decouple the scaling from resolution, and render the icons at 1.5x scaling compared to what OG NT size would render at 1920x1080. And `1.0` would render at the same scale as OG NT would for 1920x1080, regardless of what your resolution is.

I think at the very least the aspect ratio of the image should remain, the squad marker looks very squished on a 4:3 monitor

2024-08-01 13:05 UTC, brysondev requested changes
![image](https://github.com/user-attachments/assets/97b4e06c-f895-42f9-b049-03868112e360)
![image](https://github.com/user-attachments/assets/659c0cfd-2e4b-41e2-bdfc-743567f94afa)

Timer seems to resize upon changing to empty squad.

2024-08-09 09:22 UTC, brysondev approved these changes
Looks good to me

2024-08-18 19:56 UTC, nullsystem commented on mp/src/game/client/neo/ui/neo_hud_round_state.cpp
> +					V_snprintf(squadMateText, SQUAD_MATE_TEXT_LENGTH, "%s %s  [%s]  Integrity %i\0", g_PR->GetPlayerName( i ), squadMateRankName, squadMateClass, squadMateHealth);
There's no point of the `\0` at the end when it's already applied for C strings. But not going to prevent the PR just for this.

2024-08-18 19:56 UTC, nullsystem approved these changes

2024-08-19 14:20 UTC, merged