WIP: Root menu - Refactor to IMGUI, Replace serverlist + new game panels
NeotokyoRebuild/neo pull request #554
Opened 2024-08-15 20:24 UTC by nullsystem

## Description
This primarily refactor the custom UI to IMGUI-style, further reducing dependencies on the whole VGUI::Panel OOP structure to just re-routing to the non-OOP immediate-mode GUI API style structure. This further continues the root menu override and goes towards the server list and new games panels.

### DONE
- ** **
- New game panel replacement
- Maplist picker
- Server list panel replacement
- Wide adjusted to fit better on 4:3, now adjusted to 4:3 width only any resolution ratio
- Some server list filters
- Changed keyboard navigation behavior, now F1-F3 for panel-tab, TAB changed to changing "sections", now have hover vs focus differentiation. Gameserver will have different kind of focus behavior to others.

### IMGUI TODO
- [ ] Tab to go between sections
- [ ] Label's font control
- [ ] Hover vs focus

### TODO
- [ ] Server (more) details dialog
- [ ] Server details shown in main menu while in-game
- [ ] Password protected server, password popup dialog
- [ ] Fix console toggle causing issue with ESC bind
- [ ] Server blacklist
- [ ] Throw in some extra filters? (EX: Ping)
- [ ] Reload on first usage of serverlist tab
- [ ] Replace playerlist/mute dialog
- [ ] Replace quit dialog

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

- related #539

## Example Screenshots
Find server screenshot:
![2024-08-10T215228_screen](https://github.com/user-attachments/assets/c0971032-5ce2-466a-a546-3a6ac0df8e39)

2024-09-07 17:32 UTC, AdamTadeusz commented
![image](https://github.com/user-attachments/assets/04951d6f-573d-4ce4-950c-8b2ab763928b)
![image](https://github.com/user-attachments/assets/5c51704c-0171-40b5-a74a-90f03f303c44)

2024-09-07 17:36 UTC, AdamTadeusz commented
![image](https://github.com/user-attachments/assets/2e027a5b-a575-4b78-b9f2-5b24ede363c6)
Also this should probably be aligned

2024-09-07 17:41 UTC, AdamTadeusz commented
https://github.com/user-attachments/assets/1faf6968-8553-4398-b189-5f1ad0a728e1

value displayed depends on what I have under the cursor

2024-09-07 17:42 UTC, AdamTadeusz commented
![image](https://github.com/user-attachments/assets/a4fef9fb-0728-42e6-bd49-019749d2eeee)
I have to double left click to enter stuff into the input field, but 90% of the time the box gets deselected on the second click so nothing happens, very tricky to enter a text field. Also I cannot delete text I entered into the field

2024-09-07 17:46 UTC, AdamTadeusz commented
https://github.com/user-attachments/assets/e2d61c79-8e3f-46d7-99c0-2a29391f207e

When a field is selected, switching between tabs does not deselect that field, probably should be the case?

2024-09-07 17:53 UTC, AdamTadeusz commented
![image](https://github.com/user-attachments/assets/05a136d7-01a4-4eee-aeda-5a9858a2ca54)
If I clear my fake name using the legacy options menu, the fake name in the new menu is stuck as this pipe symbol for some time

2024-09-07 17:57 UTC, AdamTadeusz commented
![image](https://github.com/user-attachments/assets/9bf00afc-67a1-4927-b757-30325557d902)
ekhm hello?

2024-09-07 17:59 UTC, AdamTadeusz commented
Also probably shouldn't be using pitch black for the button background, it's a very striking colour, maybe add like 10 to each colour channel to mimick the colour used in the current scope overlay? 
![image](https://github.com/user-attachments/assets/8ad7233a-8688-4100-a07b-038dc320a288)

2024-09-07 20:14 UTC, nullsystem commented
> Screen.Recording.2024-09-07.183934.mp4
> 
> value displayed depends on what I have under the cursor
> 
> [Edit] this happens when I have no custom name selected

That's odd, it's supposed to be your Steam name if nothing custom given.

2024-09-07 20:17 UTC, nullsystem commented
> ![image](https://private-user-images.githubusercontent.com/44210793/365389575-05a136d7-01a4-4eee-aeda-5a9858a2ca54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3Mzk5NDAsIm5iZiI6MTcyNTczOTY0MCwicGF0aCI6Ii80NDIxMDc5My8zNjUzODk1NzUtMDVhMTM2ZDctMDFhNC00ZWVlLWFlZGEtNWE5ODU4YTJjYTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIwMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZDVmNWY3NjQyMzgzYjZlNjkzOTU2MGRjN2Q3ODc1OWIxNWE2OWEwOTdjODE1NzMyMzVmMTc1ZDY2ZTA0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NZ2Eu1b-_KCDi74nmCkwdRS7bmikPYcDz5HP6V_O8ec) If I clear my fake name using the legacy options menu, the fake name in the new menu is stuck as this pipe symbol for some time

I don't get this one. The string used in the menu is separate from the ConVar and only fetch/applied on load/save settings. Neither could I replicate what you've stated?

2024-09-07 20:23 UTC, AdamTadeusz commented
> > ![image](https://private-user-images.githubusercontent.com/44210793/365389575-05a136d7-01a4-4eee-aeda-5a9858a2ca54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3Mzk5NDAsIm5iZiI6MTcyNTczOTY0MCwicGF0aCI6Ii80NDIxMDc5My8zNjUzODk1NzUtMDVhMTM2ZDctMDFhNC00ZWVlLWFlZGEtNWE5ODU4YTJjYTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIwMDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZDVmNWY3NjQyMzgzYjZlNjkzOTU2MGRjN2Q3ODc1OWIxNWE2OWEwOTdjODE1NzMyMzVmMTc1ZDY2ZTA0MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NZ2Eu1b-_KCDi74nmCkwdRS7bmikPYcDz5HP6V_O8ec) If I clear my fake name using the legacy options menu, the fake name in the new menu is stuck as this pipe symbol for some time
> 
> I don't get this one. The string used in the menu is separate from the ConVar and only fetch/applied on load/save settings. Neither could I replicate what you've stated?
> 
> If you use the legacy options menu to change to a different name than what was in the new menu, and maybe you need to have input for the fake name in the new menu active. ![image](https://private-user-images.githubusercontent.com/44210793/365399008-db2b618a-1f2e-44b5-8361-4563778173ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDA4NzYsIm5iZiI6MTcyNTc0MDU3NiwicGF0aCI6Ii80NDIxMDc5My8zNjUzOTkwMDgtZGIyYjYxOGEtMWYyZS00NGI1LTgzNjEtNDU2Mzc3ODE3M2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIwMjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZTMyZjRjMjdiNzZkNmIyZDM1NTJkYWMzZmFmMDRkMzhkNDMxY2ViZGU1NDZmYThhZmFiZjhiYzYxYjIxMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2GKHjK6cFnVXIVW_dhnb7_WjVrV_cyA2szF_qrAzi74) Also displays the pipe symbol when you back out of options even though in the legacy menu it shows I have no fake name selected ![image](https://private-user-images.githubusercontent.com/44210793/365399049-c00e1c95-a359-49a1-b3ae-1227971e829b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3NDA4NzYsIm5iZiI6MTcyNTc0MDU3NiwicGF0aCI6Ii80NDIxMDc5My8zNjUzOTkwNDktYzAwZTFjOTUtYTM1OS00OWExLWIzYWUtMTIyNzk3MWU4MjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDIwMjI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4OWRlN2Q0MTlhN2I4YWM3MmJiNGNhZjg3ZGU5OTBmM2MzNTg3NDRiMGE3MzBjNjQwOTk3MDA2YThlOTRlN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFwiscX_4UvuL9eSLKswQ4NZhAwr30Xi34kqaBdgH3Q)

oh shit mb i edited your comment wtf

2024-09-08 11:03 UTC, nullsystem commented
@AdamTadeusz Can confirm Windows couldn't use %s on wchar_t printf, so just converting them prior usage instead.

2024-09-08 12:07 UTC, nullsystem commented
> ![image](https://private-user-images.githubusercontent.com/44210793/365388912-a4fef9fb-0728-42e6-bd49-019749d2eeee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3OTc0NDQsIm5iZiI6MTcyNTc5NzE0NCwicGF0aCI6Ii80NDIxMDc5My8zNjUzODg5MTItYTRmZWY5ZmItMDcyOC00MmU2LWJkNDktMDE5NzQ5ZDJlZWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDEyMDU0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYzMyNjYzZjFjNTQ4NzQyODk2YTY2YzU1NGFhZGEyMzRjN2U0YmRkZjY3Yjk2NjJhNGUyYjc2OTdjNGE3ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lCbMPZSqDgO8j80N7k-CC81XwsetyVgVg0rKYz17ncE) I have to double left click to enter stuff into the input field, but 90% of the time the box gets deselected on the second click so nothing happens, very tricky to enter a text field. Also I cannot delete text I entered into the field
> 
> I would also expect to be able to use the arrow keys/ cursor to position where text is entered/deleted
> 
> [Edit] probably a case of the double click time-out being way to short

Probably colliding with single-click but I just changed it to single-click for TextEdit, which was the behavior for the original vgui textedit panel anyway.

2024-09-08 13:02 UTC, AdamTadeusz approved these changes

2024-09-12 11:48 UTC, Masterkatze requested changes
It looks and works good in game (with some minor improvements? see my screenshots later), the code overall LGTM too, but I still found some things that require some changes in my opinion. It also will benefit from code splitting to separate files (neo_root.cpp for example).

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/OverrideInterface.cpp
> +	void Create( vgui::VPANEL parent )
Missing `override` keyword, same thing for `GetPanel` and `Destroy`.

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/OverrideInterface.cpp
> +			MainMenu->SetParent( (vgui::Panel *)NULL );
`nullptr` instead of `(vgui::Panel *)NULL`?

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/neo_root.cpp
> +						const int yPos = g_uiCtx.iYOffset[g_uiCtx.iSection] - g_uiCtx.iRowTall;
`yPos` is unused.

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/OverrideInterface.cpp
> +	CNeoRoot *MainMenu;
`CNeoRoot *MainMenu = nullptr;`?

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/neo_root.cpp
> +		break; case GSIW_LOCKED:
What a weird style lol with this `break;` in front of `case`, can we use the "normal" one as in the next `switch` case on the line 189?

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/neo_root.cpp
> +		pAudio->bMicBoost = (engine->GetVoiceTweakAPI()->GetControlFloat(MicBoost) != 0.0f);
Use `>` instead of `!=` with float?

2024-09-12 11:48 UTC, Masterkatze commented on mp/src/game/client/neo/ui/neo_root.cpp
> +			-1, 0, 2,
Magic numbers - what do they mean?

2024-09-12 11:51 UTC, Masterkatze commented
Some bikeshedding:

I think it will be better to move the voice activity slider to the right (behind the `Stop testing`):
![Screenshot_20240912_103739](https://github.com/user-attachments/assets/25d28879-2c42-4f81-8212-d8c6627634c9)

Move display name value to the right for the sake of consistency?
![Screenshot_20240912_104300](https://github.com/user-attachments/assets/1e62a587-a801-4c18-b302-1cdce9bae30e)

2024-09-12 19:42 UTC, nullsystem commented
@Masterkatze @AdamTadeusz Applied Masterkatze review changes which includes splitting settings and serverlists out of neo_root into separate files. Also fixed/improved mic tester and slider left/right buttons.

2024-09-13 07:55 UTC, Masterkatze approved these changes

2024-09-13 10:39 UTC, AdamTadeusz approved these changes

2024-09-13 17:00 UTC, merged