Don't drain AUX in underwater
NeotokyoRebuild/neo pull request #557
Opened 2024-08-19 21:28 UTC by nullsystem

## Description

* Just a quick ifndef out the device that starts/ends the drain
* NOTE: Might want to really separate "NT aux" from "suit power" in the future, but this is good enough for now

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #529

2024-08-19 21:31 UTC, AdamTadeusz commented
genius xD

2024-09-03 14:24 UTC, AdamTadeusz approved these changes

2024-09-03 18:42 UTC, AdamTadeusz requested changes
I would remove the  -fixes #530

2024-09-03 18:45 UTC, nullsystem commented
@AdamTadeusz Oh, so aux is tied to the water damage in OG:NT...

2024-09-03 18:54 UTC, AdamTadeusz commented
It's not tied to aux, im just trying to not get swept away by the current. But you definitely start taking damage later and take less damage per tick. Damage taken also seems to either be a bit random or some kind of innacuracy between ticks because sometimes you take 6 and sometimes 7 damage

2024-09-03 19:42 UTC, nullsystem commented
@AdamTadeusz Ok OG:NT's damage certainly looks like a mix of 6 and 7. I mean I'd rather just stick with a fixed number rather than replicating this randomness...

2024-09-03 20:09 UTC, nullsystem commented
@AdamTadeusz Actually it does seems like it is increasing from a min to maximum value. Adjusted the value that seems to behave close.

2024-09-04 11:30 UTC, AdamTadeusz commented
In the original a recon takes between 8 and 7 damage and a support takes between 4 and 3 damage, So I guess the class damage modifier applies to drowning damage too

2024-09-04 11:34 UTC, AdamTadeusz commented
Also unrelated but you can initiate a sprint in the original when airborne, swimming and on the floor in water, none of which works in ntre

2024-09-07 14:37 UTC, nullsystem commented
@AdamTadeusz I've differ the modifier by class now, although isn't exact due to OG:NT's odd varying damages where NT;RE is consistent, it's close neough.

2024-09-07 15:31 UTC, AdamTadeusz approved these changes

2024-09-09 08:55 UTC, brysondev approved these changes

2024-09-09 08:55 UTC, brysondev commented
![image](https://github.com/user-attachments/assets/f84054c2-53c1-439a-8e0c-faf44c0466c8)

LGTM

2024-09-09 17:17 UTC, merged