NeoUI - Custom loading screen, wrapped text
NeotokyoRebuild/neo pull request #677
Opened 2024-10-04 21:17 UTC by nullsystem

## Description
* Re-route the old VGUI text/progress into NeoUI
* Loading vs disconnect states by title locale index
* Single-progress bar as 2nd one not used
* Preload map name if known (serverlist + new game)
* `NeoUI::LabelWrap` for a wrapped version of a label

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

- fixes #603

2024-10-09 08:05 UTC, AdamTadeusz submitted a review, later dismissed

2024-10-09 08:06 UTC, AdamTadeusz requested changes
Should g_pNeoLoading be deleted and the value of the pointer reset in ~ClientModeShared()

2024-10-11 18:19 UTC, AdamTadeusz approved these changes

2024-10-12 09:53 UTC, brysondev approved these changes

2024-10-12 09:56 UTC, merged