[WIP] Deathmatch gamemode
NeotokyoRebuild/neo pull request #694
Opened 2024-10-12 00:07 UTC by nullsystem

## Description
* **DRAFT: The general gameplay of DM works, however UI-wise still WIP**
* Deathmatch spawning
    * Use info_player_deathmatch entity if possible
    * Otherwise can just use the separate file (dmspawn)
    * 
* Deathmatch gameplay
    * Either to maximum XP or time runs out
    * If tying at max XP or post time out, it'll end when there's a single highest XP winner
* UI
    * HUD round state adjusted for DM
    * On spawning, a menu popup to dismiss/change/dismiss for the entire match
* ConVars
    * neo_sv_dmspawn_useent - Default 0, override to use map's deathmatch spawn entity over the dmspawn loc file
    * neo_sv_dm_max_class_dur - Default 5s, maximum duration you're allowed to pick a class post-spawning in
    * neo_dm_round_timelimit - Timelimit for deathmatch
    * neo_sv_dm_win_xp - Default 50, if 0 disable XP win limit
* ConCommands - Here's the commands to edit dmspawn loc files and check on it. Used only for local server.
    * neo_sv_dmspawn_create - Create a dmspawn spawn
    * neo_sv_dmspawn_removeall - Remove all dmspawn spawns
    * neo_sv_dmspawn_printlocs - Print all coordinates of the dmspawn spawns
    * neo_sv_dmspawn_save - Save the map's loc dmspawn file
    * neo_sv_dmspawn_load - Load the map's loc dmspawn file
    * neo_sv_dmspawn_teleportnext - Teleport to the next dmspawn spawn
    * neo_sv_dmspawn_mapinfo - Check amount of dmspawn spawns and if it can DM

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #691

2024-10-15 21:57 UTC, brysondev requested changes

2024-10-15 21:57 UTC, brysondev commented on mp/src/game/server/neo/neo_player.cpp
> +			&& m_aliveTimer.IsLessThen(5.f))
Is this persistent after the user fires? That and 5 seconds is generous 🤔

2024-10-16 00:16 UTC, brysondev approved these changes

2024-10-16 10:51 UTC, AdamTadeusz commented
Would it be worth giving players a few seconds of invulnerability after spawning?

2024-10-16 11:07 UTC, AdamTadeusz commented
> > Would it be worth giving players a few seconds of invulnerability after spawning?
> 
> https://github.com/NeotokyoRebuild/neo/pull/694/files#diff-c4ea17be8fcce45e76e46a0f050cbdc12308a47653133f08ee36d7fbdf9e181dR1667
> 
> He is, but it's only until they fire or the timer expires. Or do you mean it's not worth giving invuln?

my bad, bots start shooting instantly by default so i didnt notice

2024-10-16 11:09 UTC, AdamTadeusz commented
I do think it would be worth if the spawns saved the player's look direction though. If you're placing a spawn in a corner you probably don't want the player on spawn to face into a wall

2024-10-16 12:09 UTC, AdamTadeusz commented
@nullsystem do you have an example map with player_info_deathmatch entities to test whether spawning on those works too?

2024-10-16 12:18 UTC, nullsystem commented
> @nullsystem do you have an example map with player_info_deathmatch entities to test whether spawning on those works too?
> 
> [Edit] nvm works on dm_lockdown

I do plan on releasing zigzag with dm entity spawn soon anyway and probably a dmspawn file for oilstain, both for playtesting this normally

2024-10-16 12:18 UTC, AdamTadeusz commented
https://github.com/user-attachments/assets/3145b5ab-5836-49db-812a-7c86f1b4f426

Shame we decoupled both aux and sprint from these, maybe the energy packs could refill your thermoptic cloak

2024-10-16 12:24 UTC, AdamTadeusz submitted a review, later dismissed

2024-10-16 18:20 UTC, nullsystem commented
@AdamTadeusz @brysondev I've added in y-look-angle for each DMSpawn spawn now

2024-10-16 18:23 UTC, brysondev approved these changes

2024-10-16 19:03 UTC, AdamTadeusz approved these changes

2024-10-16 20:00 UTC, merged