enlarge text for >=1440p resolutions
NeotokyoRebuild/neo pull request #699
Opened 2024-10-12 12:24 UTC by brysondev

## Description

Upscale font sizes for high-resolution monitors
## Toolchain

- Windows MSVC VS2022

Preview:

![4K Options page](https://github.com/user-attachments/assets/57abf25f-96cb-4bcd-b5b3-02e6c3458737)
![4K Main Menu](https://github.com/user-attachments/assets/a69c26e9-4ca8-4196-8b89-11bcc6a84784)
<img width="1192" alt="4K In-Game Chat" src="https://github.com/user-attachments/assets/50f19b40-d464-4875-bb6a-915058045308">

2024-10-12 14:55 UTC, AdamTadeusz requested changes

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
shouldn't this start at 1441?

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
ditto

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
ditto

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
you get the idea

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
mhm

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
yup still there

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/ClientScheme.res
> +				"yres"	"1536 1599"
*burps*

2024-10-12 14:55 UTC, AdamTadeusz commented on mp/game/neo/resource/chatscheme.res
> +				"yres"	"1536 1600"
and finished

2024-10-12 15:08 UTC, AdamTadeusz submitted a review, later dismissed

2024-10-13 15:51 UTC, AdamTadeusz approved these changes

2024-10-13 22:21 UTC, nullsystem approved these changes
Well, it didn't negatively affect 480p, 720p, and 1080p

2024-10-13 22:43 UTC, merged