Damage/killer info duration 60s->10s + Dismiss forever
NeotokyoRebuild/neo pull request #718
Opened 2024-10-13 15:32 UTC by nullsystem

## Description
* 60s was too long, turned down to 10s
* Add the ability to dismiss and not have the info for the rest of the match

## Toolchain

- Linux GCC Distro Native Arch/GCC 14

## Linked Issues

* fixes #717

2024-10-13 15:35 UTC, brysondev submitted a review, later dismissed

2024-10-13 16:35 UTC, Rainyan requested changes

2024-10-13 16:35 UTC, Rainyan commented on mp/src/game/server/neo/neo_player.cpp
> +			WRITE_SHORT(static_cast<short>(((m_iDmgMenuNextPage ? 0b11 : 1) | 1 << 8))); // Amount of options
What does the magic bitwise math do here? Any chance we could have a constant expression for this to make the intent of the passed data more obvious?

2024-10-13 16:35 UTC, Rainyan commented on mp/src/game/server/neo/neo_player.cpp
> +			case 9: // Do not show again
Could we have an enumeration instead of magic values + comments, to make this clearer

2024-10-13 16:35 UTC, Rainyan commented on mp/src/game/server/neo/neo_player.cpp
>  	static const int TOTALLINE_LEN = 64; // Rough-approximate
Could be constexpr

2024-10-13 18:16 UTC, brysondev approved these changes
Enums my beloved

2024-10-15 17:04 UTC, Rainyan approved these changes
We might wanna eventually move the HUD "never show" option as part of the client's FCVAR_USERINFO, so the preference is not tied to the gamerules entity lifetime, and can be set with a config file by the user.

2024-10-15 17:12 UTC, merged