Hide own view model on death
NeotokyoRebuild/neo pull request #719
Opened 2024-10-13 15:34 UTC by AdamTadeusz

## Description

Will fix the issue where after death your own view model remains visible in the spot where you died. No clue what caused it initially, this is a workaround I guess.

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes own view model visible after death

2024-10-13 15:37 UTC, brysondev submitted a review, later dismissed
mmmmm yummy random jank appearing 🤤

2024-10-15 19:08 UTC, Rainyan requested changes
This seems to be a regression from 31044a92 as per git bisect (bad `v9.0-prealpha`, good `v8.1-prealpha`).

I would instead suggest:

```diff
diff --git a/mp/src/game/server/neo/neo_player.cpp b/mp/src/game/server/neo/neo_player.cpp
index 5ab5382a..a554c0d8 100644
--- a/mp/src/game/server/neo/neo_player.cpp
+++ b/mp/src/game/server/neo/neo_player.cpp
@@ -1887,11 +1887,12 @@ void CNEO_Player::Weapon_Drop( CBaseCombatWeapon *pWeapon,
                }
        }
 
-       if (!pWeapon)
-               return;
+       if (pWeapon)
+       {
+               pWeapon->m_bInReload = false;
+               pWeapon->StopWeaponSound(RELOAD_NPC);
+       }
 
-       pWeapon->m_bInReload = false;
-       pWeapon->StopWeaponSound(RELOAD_NPC);
        BaseClass::Weapon_Drop(pWeapon, pvecTarget, pVelocity);
 }
```

as the early return from the `BaseClass::Weapon_Drop` chain responsible for the VM nodraw application here seems to be the root cause of the bug.

2024-10-16 10:11 UTC, brysondev approved these changes

2024-10-16 10:26 UTC, Rainyan approved these changes

2024-10-16 10:42 UTC, merged