Animation tweaks
NeotokyoRebuild/neo pull request #726
Opened 2024-10-14 13:54 UTC by AdamTadeusz

## Description

jinrai recon leg animations when sprinting work in all directions now, all upper body animations plays animation when idle or walking

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

- fixes #
- related #

2024-10-14 13:56 UTC, brysondev commented on mp/src/game/shared/Multiplayer/multiplayer_animstate.cpp
> +		if (m_LegAnimType != LEGANIM_9WAY) // NEO JANK (Adam) Doing this fixes the client side jinrai recon west running animations. NEO TODO (Adam) workaout correct leg animation type, or why these are br
nit
```suggestion
		if ( m_LegAnimType != LEGANIM_9WAY ) // NEO JANK (Adam) Doing this fixes the client side jinrai recon west running animations. NEO TODO (Adam) workaout correct leg animation type, or why these are broken
```

2024-10-14 13:56 UTC, brysondev submitted a review, later dismissed

2024-10-14 14:05 UTC, brysondev approved these changes

2024-10-25 15:26 UTC, Rainyan requested changes

2024-10-25 15:26 UTC, Rainyan commented on mp/src/game/shared/hl2mp/hl2mp_playeranimstate.cpp
> +	if (m_pHL2MPPlayer->IsSprinting())
We could probably move the `vecVelocity` math inside the `else` condition scope, so it doesn't need to be calculated for the `->IsSprinting()` case.

2024-10-26 17:53 UTC, Rainyan approved these changes

2024-10-26 21:03 UTC, brysondev approved these changes

2024-10-26 21:12 UTC, merged