Thermals V3
NeotokyoRebuild/neo pull request #776
Opened 2024-11-01 20:34 UTC by AdamTadeusz

## Description

-------> SHADERS AND NEW MATERIALS IN https://github.com/NeotokyoRebuild/neoAssets/pull/15 <-------

Added noise to the thermals;

Reduced initial thermal shader colour gradient offset to make dark objects stand out a bit more (using black screen with default colour of 0 0 0 to work out what I believe is the correct value) and added a multiplier to compensate for bright areas not being as bright with the offset reduction;

View models and other models now use the tvmgrad and tvmgrad2 textures respectively to colour correct. This methodology can probably be used in the night vision and especially the motion vision to get a more original colour and also make those shaders more performant and less complicated (see materials/dev/nvgrad.vtf and materials/dev/mvgrad.vtf);

The way the gradients are passed from the material to the shader can also probably be used to remove the janky way that thermoptic cloak's strength is passed to the thermoptic shader, instead of through the current modification of a convar everytime a cloaked object is drawn

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

2024-11-02 13:49 UTC, brysondev submitted a review, later dismissed

2024-11-02 13:49 UTC, brysondev commented on mp/src/materialsystem/stdshaders/neo_thermalvision_ps30.fxc
> +	const float noise =  0.9 + (tex2D(NoiseTexture, i.texCoord + float2(g_XNoiseOffset, g_YNoiseOffset)) / 10);
Nit tabs

2024-11-02 13:49 UTC, brysondev commented on mp/src/materialsystem/stdshaders/neo_thermalvision_ps30.fxc
>  	const float4 fbColor = tex2D(FrameBuffer, i.texCoord);
Nit tabs

2024-11-24 23:11 UTC, Rainyan requested changes

2024-12-10 19:03 UTC, AdamTadeusz commented on mp/src/materialsystem/stdshaders/Neo_ThermalVision.cpp
> +SHADER_PARAM(NOISETRANSFORM, SHADER_PARAM_TYPE_VEC3, "Vector(0, 0, 0)", "")
This tutorial https://developer.valvesoftware.com/wiki/Source_SDK_2013:_Your_Second_Shader uses brackets, I've also seen just a few numbers with no brackets somewhere else in the wiki

2024-12-10 19:43 UTC, brysondev approved these changes

2024-12-12 09:37 UTC, Rainyan approved these changes
:+1:

2024-12-12 10:33 UTC, merged