player collisions single command
NeotokyoRebuild/neo pull request #789
Opened 2024-11-03 11:11 UTC by AdamTadeusz

## Description

One command to control collision method, Bitwise AND, better description to reflect actual behavior (Boosting already worked both on enemies and friendlies regardless of enemy only collision).

Collision options are ordered in terms of how disruptive they are, with enemy only collisions considered more disruptive than boosting, and the combination of the two being the most disruptive.

## Toolchain

- Windows MSVC VS2022
- Linux GCC Distro Native [Specify distro + GCC version]
- Linux GCC 10 Sniper 3.0

## Linked Issues

2024-11-05 16:16 UTC, brysondev approved these changes

2025-02-17 22:31 UTC, nullsystem requested changes

2025-02-17 22:31 UTC, nullsystem commented on mp/src/game/shared/util_shared.cpp
> +			if (sv_neo_player_collisions.GetInt() & 1)
Nit: Can you give those 1/2 numbers as an enum so it makes it more clear which bitwise flag check is for

2025-02-18 18:10 UTC, brysondev approved these changes

2025-02-24 11:12 UTC, brysondev submitted a review, later dismissed

2025-03-01 20:01 UTC, DESTROYGIRL approved these changes

2025-03-02 10:34 UTC, merged